baseURL = "https://blognot.co/"
#disqusShortname = "blognot"
googleAnalytics = "UA-11591143-1"
languageCode = "ru"
defaultContentLanguage = "ru"
title = "БлоGнот"
theme = "mainroad"
paginate = "15"
rssLimit = "25"
#ignoreFiles = ["\\.jpg$","\\.png$","\\.webp$","\\.gif$","\\.jpeg$"]

[Params]
dateformat = "02-01-2006"
opengraph = true
pager = true
post_meta = ["date"]
readmore = true
schema = true
twitter_cards = true
[Params.sidebar]
home = "right"
list = "left"
single = "right"
widgets = ["search", "recent", "comments","taglist", "social", "languages"]
[Params.style.vars]
fontFamilyPrimary = "BlinkMacSystemFont,-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif"
[Params.widgets]
recent_num = 7
tags_counter = true
[Params.widgets.social]
facebook = "sergey.petrenko"
instagram = "grayru"
linkedin = "username"
telegram = "blognot"
twitter = "gray_ru"
[[Params.widgets.social.custom]]
icon = "svg/youtube.svg"
title = "Youtube"
url = "https://www.youtube.com/c/grayru"
[markup.goldmark.renderer]
enableEmoji = true
summarylength = 200
unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "Обо мне"
    url = "/about/"
    weight = -110
