baseURL = "/"
languageCode = "ru"
defaultContentLanguage = "ru"
title = "БлоGнот"
theme = "mainroad"
paginate = "10"
googleAnalytics = "UA-11591143-1"
disqusShortname = "blognot"

[markup.goldmark.renderer]
unsafe= true


summarylength = 200
enableEmoji = true

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "taglist", "social", "languages"]

  [Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "sergey.petrenko"
  twitter = "gray_ru"
  instagram = "grayru"
  linkedin = "username"
  telegram = "blognot"

# Custom social links
[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://www.youtube.com/c/grayru"
  icon = "svg/youtube.svg" # Optional. Path relative to "layouts/partials"

[Params]
opengraph = true # Enable OpenGraph if true
schema = true # Enable Schema
twitter_cards = true # Enable Twitter Cards if true
readmore = true # Show "Read more" button in list if true
pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
post_meta = ["date"]
dateformat = "02-01-2006"

[Params.style.vars]
fontFamilyPrimary = "BlinkMacSystemFont,-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif"
