name: Hugo S3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
    - uses: klakegg/actions-hugo@1.0.0
      with:
        command: --minify
    - uses: up9cloud/action-rsync@master
      env:
        HOST: remark.blognot.co
        KEY: ${{secrets.DEPLOY_SSH_KEY}}
        TARGET: /var/remark/web
        SOURCE: ./public/
        VERBOSE: true
        
        PRE_SCRIPT: |
          echo start at:
          date -u
        POST_SCRIPT: "echo done at: && date -u"
